{{ if .Values.opentelemetryCollector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olly-collector.name" . }}-opentelemetry-collector
  labels:
    {{- include "olly-collector.labels" . | nindent 4 }}
{{ end }}
